# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuitBlack
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSBlack
  groupBy: "Jumpsuit" # Exodus-Better-Loadout

- type: loadout
  id: HeadofSecurityJumpskirtBlack
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSBlack
  groupBy: "Jumpskirt" # Exodus-Better-Loadout

    #Shoulder Mantle
- type: loadout
  id: HeadofSecurityShoulderMantle
  equipment:
    neck: ClothingNeckMantleHOSShoulder
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS
