- type: job
  id: MedicalDoctor
  name: job-name-doctor
  description: job-description-doctor
  playTimeTracker: JobMedicalDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 #2 hrs # Corvax-RoleTime
    # Exodus-Better-Med-Hiring-Start
    - !type:TraitsRequirement
      inverted: true
      traits:
      - Muted
      - Blindness
      - Narcolepsy
    # Exodus-Better-Med-Hiring-End
  startingGear: DoctorGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen

- type: startingGear
  id: DoctorGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  #storage:
    #back:
    #- Stuff
