using Robust.Client.ResourceManagement;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.State;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Map;
using Serilog;
using System.Numerics;

namespace Content.Client.Damage.UI;

[GenerateTypedNameReferences]
public sealed partial class StaminaUI : UIWidget
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private float _scale = 4.0f;

    public StaminaUI()
    {
        RobustXamlLoader.Load(this);

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        ChargeBar.BackgroundStyleBoxOverride = new StyleBoxTexture()
        {
            Texture = _resourceCache.GetResource<TextureResource>("/Textures/Exodus/Interface/Stamina/stamina_bar.png"),
            TextureScale = new Vector2(_scale, _scale),
            Mode = StyleBoxTexture.StretchMode.Tile
        };
        ChargeBar.ForegroundStyleBoxOverride = new StyleBoxTexture()
        {
            Texture = _resourceCache.GetResource<TextureResource>("/Textures/Exodus/Interface/Stamina/stamina_bar_value.png"),
            TextureScale = new Vector2(_scale, _scale),
            Mode = StyleBoxTexture.StretchMode.Tile
        };
    }

    public void SetValue(float value)
    {
        ChargeBar.Value = value;
    }
}
