contact_links:
  - name: Предложение
    url: https://discord.space-exodus.com
    about: Свои предложения можете оставлять в соответствующем канале Discord.
  - name: Сообщить об уязвимости
    url: https://discord.space-exodus.com
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности @lokilife (739649545163636918) в Discord.
