# Jumpsuit
# Head
- type: loadout
  id: HeadofSecurityHeadCap
  equipment:
    head: ClothingHeadHatCapHoS

# Neck
- type: loadoutEffectGroup
  id: SpecialistHoS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 144000 #40 hrs

- type: loadout
  id: HeadofSecurityClothingNeckCloakFur
  equipment:
    neck: ClothingNeckCloakHosFur
  effects:
  - !type:GroupLoadoutEffect
    proto: SpecialistHoS

# OuterClothing
- type: loadout
  id: HeadofSecurityOvercoat
  equipment:
    outerClothing: ClothingOuterCoatSecurityOvercoat
  groupBy: "Armor"

#Ears
- type: loadout
  id: HeadofSecurityAltHeadset
  equipment:
    ears: ClothingHeadsetAltSecurity

- type: loadout
  id: HeadofSecurityHeadset
  equipment:
    ears: ClothingHeadsetSecurityHOS
