# Jumpsuit
# Head
- type: loadout
  id: HeadofSecurityHeadCap
  equipment:
    head: ClothingHeadHatCapHoS

# Neck
- type: loadoutEffectGroup
  id: SpecialistHoS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 144000 #40 hrs

- type: loadout
  id: HeadofSecurityClothingNeckCloakFur
  equipment:
    neck: ClothingNeckCloakHosFur
  effects:
  - !type:GroupLoadoutEffect
    proto: SpecialistHoS

# OuterClothing
- type: loadout
  id: HeadofSecurityOvercoat
  equipment:
    outerClothing: ClothingOuterCoatSecurityOvercoat
  groupBy: "Armor"

# Gun
- type: loadout
  id: SecurityGunMateba
  dummyEntity: LoadoutDummyWeaponRevolverMateba
  equipment:
    pocket1: WeaponRevolverMateba
    pocket2: SpeedLoaderMagnum
  groupBy: "GunRevolver"

- type: loadout
  id: SecurityGunDeckard
  dummyEntity: LoadoutDummyWeaponRevolverDeckard
  equipment:
    pocket1: WeaponRevolverDeckard
    pocket2: SpeedLoaderMagnum
  groupBy: "GunRevolver"

- type: loadout
  id: SecurityGunInspector
  dummyEntity: LoadoutDummyWeaponRevolverInspector
  equipment:
    pocket1: WeaponRevolverInspector
    pocket2: SpeedLoaderMagnum
  groupBy: "GunRevolver"

- type: loadout
  id: SecurityGunMk58
  dummyEntity: LoadoutDummyWeaponPistolMk58
  equipment:
    pocket1: WeaponPistolMk58
    pocket2: MagazinePistol
  groupBy: "GunPistol"

#Ears
- type: loadout
  id: HeadofSecurityAltHeadset
  equipment:
    ears: ClothingHeadsetAltSecurity

- type: loadout
  id: HeadofSecurityHeadset
  equipment:
    ears: ClothingHeadsetSecurityHOS
