# For mantles
- type: loadoutEffectGroup
  id: MasterHoS
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 72000 #20 hrs

# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
  groupBy: "Jumpsuit" # Exodus-Better-Loadout

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS
  groupBy: "Jumpskirt" # Exodus-Better-Loadout

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt
  groupBy: "Jumpsuit" # Exodus-Better-Loadout

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt
  groupBy: "Jumpskirt" # Exodus-Better-Loadout

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal
  groupBy: "Jumpsuit" # Exodus-Better-Loadout

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal
  groupBy: "Jumpskirt" # Exodus-Better-Loadout

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos
  groupBy: "Cloak" # Exodus-Better-Loadout

- type: loadout
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS
  groupBy: "Mantle" # Exodus-Better-Loadout

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench
  groupBy: "Armor" # Exodus-Better-Loadout

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS
