- type: entity
  id: BaseStation
  abstract: true
  components:
    - type: StationData

- type: entity
  id: BaseStationCargo
  abstract: true
  components:
    - type: StationBankAccount
    - type: StationCargoOrderDatabase
    - type: StationCargoBountyDatabase

- type: entity
  id: BaseStationJobsSpawning
  abstract: true
  components:
    - type: StationJobs
      availableJobs: {}
    - type: StationSpawning

- type: entity
  id: BaseStationRecords
  abstract: true
  components:
    - type: StationRecords

- type: entity
  id: BaseStationArrivals
  abstract: true
  components:
    - type: StationArrivals

- type: entity
  id: BaseStationGateway
  abstract: true
  components:
    - type: GatewayGenerator

- type: entity
  id: BaseStationShuttles
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/Shuttles/cargo.yml
    - type: GridSpawn
      groups:
        trade: !type:GridSpawnGroup
          nameGrid: false # Exodus | Normal name for trading outpost grid
          addComponents:
            - type: ProtectedGrid
            - type: TradeStation
          paths:
            - /Maps/Shuttles/trading_outpost.yml
        # Spawn last
        ruins: !type:GridSpawnGroup
          hide: true
          nameGrid: true
          minCount: 2
          maxCount: 2
          stationGrid: false
          paths:
          - /Maps/Ruins/abandoned_outpost.yml
          # Corvax-Mapping-Start
          - /Maps/Corvax/Ruins/corvax_accident.yml
          - /Maps/Corvax/Ruins/corvax_adventurer.yml
          - /Maps/Corvax/Ruins/corvax_aplink.yml
          - /Maps/Corvax/Ruins/corvax_battleship.yml
          - /Maps/Corvax/Ruins/corvax_gas_station.yml
          - /Maps/Corvax/Ruins/corvax_bss_unluck.yml
          - /Maps/Corvax/Ruins/corvax_hotel_trivago.yml
          - /Maps/Corvax/Ruins/corvax_kamikaze.yml
          - /Maps/Corvax/Ruins/corvax_ore.yml
          - /Maps/Corvax/Ruins/corvax_research_station.yml
          - /Maps/Corvax/Ruins/corvax_rnd_debris.yml
          - /Maps/Corvax/Ruins/corvax_sanctus.yml
          - /Maps/Corvax/Ruins/corvax_ussp_debris.yml
          - /Maps/Corvax/Ruins/corvax_ussp_asteroid.yml
          # Corvax-Mapping-End
          - /Maps/Ruins/wrecklaimer.yml
        vgroid: !type:DungeonSpawnGroup
          minimumDistance: 300
          maximumDistance: 350
          nameDataset: NamesBorer
          stationGrid: false
          addComponents:
          - type: Gravity
            enabled: true
            inherent: true
          protos:
          - VGRoid
        # Exodus-SalvageShuttle-start
        mining: !type:GridSpawnGroup
          nameGrid: false
          paths:
          - /Maps/Exodus/Shuttles/mining.yml
        # Exodus-SalvageShuttle-end

- type: entity
  id: BaseStationCentcomm
  abstract: true
  components:
    - type: StationCentcomm
      map: "/Maps/Corvax/corvax_centcomm.yml" # Corvax-Mapping

- type: entity
  id: BaseStationEvacuation
  abstract: true
  components:
    - type: StationEmergencyShuttle

- type: entity
  id: BaseStationAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: stationAlerts

- type: entity
  id: BaseStationExpeditions
  abstract: true
  components:
    - type: SalvageExpeditionData

- type: entity
  id: BaseStationMagnet
  abstract: true
  components:
    - type: SalvageMagnetData

- type: entity
  id: BaseStationSiliconLawCrewsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Crewsimov

- type: entity
  id: BaseStationNews
  abstract: true
  components:
    - type: StationNews

- type: entity
  id: BaseStationDeliveries
  abstract: true
  components:
  - type: CargoDeliveryData

- type: entity
  id: BaseStationAllEventsEligible
  abstract: true
  components:
    - type: StationEventEligible # For when someone makes this more granular in the future.
