using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Exodus.TeleportationZone;
using Robust.Shared.Utility;
using Robust.Client.Graphics;
using Content.Client.GameTicking.Managers;
using Content.Shared.PDA;
using Robust.Shared.Utility;
using Content.Shared.CartridgeLoader;
using Content.Client.Message;
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Timing;

namespace Content.Client.Exodus.TeleportationZone.UI.Scaner;

[GenerateTypedNameReferences]
public sealed partial class TeleportationZoneScanerWindow : DefaultWindow
{
    public event Action? TeleportationZoneScanerRefreshButtonPressed;

    public TeleportationZoneScanerWindow()
    {
        RobustXamlLoader.Load(this);
        TeleportationZoneScanerRefreshButton.OnPressed += _ => TeleportationZoneScanerRefreshButtonPressed?.Invoke();
    }

    public void UpdateState(TeleportationZoneScanerUiState state)
    {
        TeleportationZoneNameLabel.Text = Loc.GetString("teleportationZone-scaner-ui-label-name", ("name", state.Name));
        TeleportationZoneXLabel.Text = Loc.GetString("teleportationZone-scaner-ui-label-x", ("x", state.X));
        TeleportationZoneYLabel.Text = Loc.GetString("teleportationZone-scaner-ui-label-y", ("y", state.Y));
        TeleportationZoneStatusLabel.SetMarkup(Loc.GetString("teleportationZone-scaner-ui-label-status", ("status", state.Status), ("color", state.Color)));
    }
}
