using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Exodus.TeleportationZone;

namespace Content.Client.Exodus.TeleportationZone.UI.Repeater;

[GenerateTypedNameReferences]
public sealed partial class TeleportationZoneRepeaterWindow : DefaultWindow
{
    public Action<string>? NameChanged;
    public string _ValidName = "unknow";

    public TeleportationZoneRepeaterWindow()
    {
        RobustXamlLoader.Load(this);
        MessageEdit.OnTextChanged += OnNameChanged;
        MessageEdit.OnTextEntered += OnNameEntered;
        MessageEdit.OnFocusExit += OnNameFocusExit;

    }

    public void UpdateState(TeleportationZoneRepeaterUiState state)
    {
        MessageEdit.Text = state.Name;
    }

    private void OnNameChanged(LineEdit.LineEditEventArgs obj)
    {
        if (obj.Text.Length == 0 ||
            string.IsNullOrWhiteSpace(obj.Text) ||
            string.IsNullOrEmpty(obj.Text))
        {
            return;
        }

        _ValidName = obj.Text;
    }

    private void OnNameEntered(LineEdit.LineEditEventArgs obj)
    {
        NameChanged?.Invoke(_ValidName);
    }

    private void OnNameFocusExit(LineEdit.LineEditEventArgs obj)
    {
        if (obj.Text.Length == 0 ||
            string.IsNullOrWhiteSpace(obj.Text) ||
            string.IsNullOrEmpty(obj.Text))
        {
            obj.Control.Text = _ValidName.Trim();
        }

        NameChanged?.Invoke(_ValidName);
    }
}
