using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Exodus.TeleportationZone;

namespace Content.Client.Exodus.TeleportationZone.UI.Beacon;

[GenerateTypedNameReferences]
public sealed partial class TeleportationZoneBeaconWindow : DefaultWindow
{

    public event Action? BeaconSaveUINCoreButtonPressed;


    public TeleportationZoneBeaconWindow()
    {
        RobustXamlLoader.Load(this);
        TeleportationZoneBeaconSaveUINCoreButton.OnPressed += _ => BeaconSaveUINCoreButtonPressed?.Invoke();
    }

    public void UpdateState(TeleportationZoneBeaconUiState state)
    {
        TeleportationZoneBeaconSaveUINCoreButton.Disabled = !state.CanSaveUINCore;
        BeaconTextureRect.TexturePath = state.TexPath;
    }
}
