using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Exodus.TeleportationZone;

namespace Content.Client.Exodus.TeleportationZone.UI.Battery;

[GenerateTypedNameReferences]
public sealed partial class TeleportationZoneBatteryWindow : DefaultWindow
{

    public Action? BatteryDownloadButtonPressed;
    public Action? BatteryUploadButtonPressed;


    public TeleportationZoneBatteryWindow()
    {
        RobustXamlLoader.Load(this);
        TeleportationZoneBatteryDownloadButton.OnPressed += _ => BatteryDownloadButtonPressed?.Invoke();
        TeleportationZoneBatteryUploadButton.OnPressed += _ => BatteryUploadButtonPressed?.Invoke();
    }

    public void UpdateState(TeleportationZoneBatteryUiState state)
    {
        TeleportationZoneBatteryDownloadButton.Disabled = !state.CanDownload;
        TeleportationZoneBatteryUploadButton.Disabled = !state.CanUnload;

        TeleportationZoneCapacityBatteryLabel.Text = Loc.GetString("teleportationZone-battery-ui-label-capacity-battery", ("amount", state.AmountMatterBattery));
        TeleportationZoneCapacitySmallBatteryLabel.Text = Loc.GetString("teleportationZone-battery-ui-label-capacity-small-battery", ("amount", state.AmountMatterSmallBattery));

        BatteryTextureRect.TexturePath = state.BatteryTexturePath;
        SmallBatteryTextureRect.TexturePath = state.SmallBatteryTexturePath;
    }
}
