// © Space Exodus, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/space-exodus/space-station-14/master/CLA.txt

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Exodus.Traits.Species.Pheromones.UI;

[GenerateTypedNameReferences]
public sealed partial class PheromonesAskWindow : DefaultWindow
{
    public event Action<string>? OnPheromonesTextSent;

    public PheromonesAskWindow()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += e => OnPheromonesTextSent?.Invoke(PheromonesTextLineEdit.Text);
    }
}
