- type: entity
  id: ActionDEV1
  name: ActionPandoraAttackBigPoint
  noSpawn: true
  components:
  - type: WorldTargetAction
    maxUseRange: 4
    minUseRange: 0
    useDelay: 1
    range: 6
    itemIconStyle: BigAction
    icon:
      sprite: Objects/Magic/magicactions.rsi
      state: spell_default
    event: !type:DelayedWorldTargetAbilityEvent
      delay: 0.1
      event: !type:WorldLineSpawnEvent
        spawnProto: AttackCellUnitPandoraFullDEBUG
        stepDelay: 0.1

- type: entity
  id: ActionDEV2
  name: ActionPandoraAttackBigPoint
  noSpawn: true
  components:
  - type: EntityTargetAction
    maxUseRange: 4
    minUseRange: 0
    useDelay: 1
    range: 4
    itemIconStyle: BigAction
    icon:
      sprite: Objects/Magic/magicactions.rsi
      state: spell_default
    event: !type:EntityAbilitiesGroupEvent
      events:
      - !type:EntityToCoordEvent
        event: !type:WorldSpawnSpellEvent
          prototypes:
          - id: AttackPandoraBigPoint
            amount: 1
          offset: 0, 0
      - !type:DelayedEntityAbilityEvent
        delay: 0.2
        event: !type:EntityToCoordEvent
          event: !type:WorldSpawnSpellEvent
            prototypes:
            - id: AttackPandoraBigPoint
              amount: 1
            offset: 0, 0
      - !type:DelayedEntityAbilityEvent
        delay: 0.4
        event: !type:EntityToCoordEvent
          event: !type:WorldSpawnSpellEvent
            prototypes:
            - id: AttackPandoraBigPoint
              amount: 1
            offset: 0, 0


- type: entity
  id: ActionDEV3
  name: ActionPandoraAttackBigPoint
  noSpawn: true
  components:
  - type: WorldTargetAction
    maxUseRange: 4
    minUseRange: 0
    useDelay: 1
    range: 40
    itemIconStyle: BigAction
    icon:
      sprite: Objects/Magic/magicactions.rsi
      state: spell_default
    event: !type:WorldMultishootEvent
      shootCnt: 3
      shootDelay: 0
      angle: 1.57
      event: !type:DirectionalLineSpawnEvent
        spawnProto: AttackCellUnitPandoraFullDEBUG
        stepDelay: 0.1

