name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write  # Required for label creation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
