- type: entity
  id: AttackCellUnitBase
  abstract: true
  placement:
    mode: SnapgridCenter
    snap:
      - Wall
  components:
  - type: Appearance
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Dynamic
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.45,-0.45,0.45,0.45"
        layer:
          - SlipLayer
        mask:
          - ItemMask
        density: 1000
        hard: false

- type: entity
  id: AttackCellUnitBaseBig
  abstract: true
  parent: AttackCellUnitBase
  placement:
    mode: SnapgridCenter
    snap:
      - Wall
  components:
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.45,-1.45,1.45,1.45"
        layer:
          - SlipLayer
        mask:
          - ItemMask
        density: 1000
        hard: false

- type: entity
  id: AttackCellUnitDamage
  abstract: true
  components:
  - type: DamageContacts
    damage:
      types:
        Heat: 10

- type: entity
  id: AttackCellUnitSlow
  abstract: true
  components:
  - type: SpeedModifierContacts
    walkSpeedModifier: 0.8
    sprintSpeedModifier: 0.8
