- type: entity
  id: AttackCellUnitBase
  abstract: true
  placement:
    mode: SnapgridCenter
    snap:
      - Wall
  components:
  - type: Appearance
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.45,-0.45,0.45,0.45"
        layer:
          - SlipLayer
        mask:
          - ItemMask
        density: 1000
        hard: false

- type: entity
  id: AttackCellUnitDespawnBase
  abstract: true
  parent: AttackCellUnitBase
  placement:
    mode: SnapgridCenter
    snap:
      - Wall
  components:
  - type: TimedDespawn
    lifetime: 0.5

- type: entity
  id: AttackCellUnitDamage
  parent: AttackCellUnitBase
  abstract: true
  components:
  - type: DamageContacts
    damage:
      types:
        Heat: 10
  - type: IgniteOnCollide
    fireStacks: 1
    count: 10

- type: entity
  id: AttackCellUnitSlow
  parent: AttackCellUnitBase
  abstract: true
  components:
  - type: SpeedModifierContacts
    walkSpeedModifier: 0.5
    sprintSpeedModifier: 0.5
